### ISSUE TITLE
Windows UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, mkdir 'pages'

### ISSUE THREAD

**Issue by RobinSCU** [vinissimus/next-translate#134]
Hi, 

when I restart my dev config "next-translate && next dev" in Jetbrains Webstorm i get the following Error:

`(node:60144) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, mkdir 'pages'
    at Object.mkdirSync (fs.js:764:3)
    at createPagesDir (C:\MYAPP\node_modules\next-translate\cli\builder.js:68:6)
    at Object.<anonymous> (C:\MYAPP\node_modules\next-translate\cli\builder.js:53:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
(node:60144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:60144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Of course the next server crashes, but at the next start the pages are getting created and everything works fine!

We can recreate the error on 3 Windows Machines.

Version used: 0.15.0

**Comment by aralroca** [comment]
It looks like a permission problem. Look at this Stackoverflow answer:

https://stackoverflow.com/a/37915233/4467741

> This is occurring because windows is not giving permission to the user to create a folder inside system drive. To solve this:
>
>Right Click 
>
> The Folder > **Properties** > **Security** Tab
>
> Click on **Edit** to change Permissions > Select the user and give **Full Control** to that user.

I hope it helps!

**Comment by RobinSCU** [comment]
Thanks for the quick answer, unfortunately not but maybe than it is an issue with our company laptops that we don't have the right permission. 

The interesting thing is for me that it can remove the files in the first start and can add dem them in the second, so it seems more like a timing issue.

**Comment by RobinSCU** [comment]
So I tried to move it to a different Partition and set the permissions, it seems to be better but the error still happens.

**Comment by aralroca** [comment]
Can you try if you can create folders using `mkdir` in your terminal? Or do you have the same Error EPERM?

**Comment by RobinSCU** [comment]
I can create the folders without an error
