### ISSUE TITLE
html lang tag does not change when changing language

### ISSUE THREAD

**Issue by haw0k** [vinissimus/next-translate#153]
SSG site, pages_/_document.js contain following code:
```
import i18nConfig from '../i18n.json'

function documentLang({ __NEXT_DATA__ }) {
  const { page } = __NEXT_DATA__
  const [, langQuery] = page.split('/')
  const lang = i18nConfig.allLanguages.find((l) => l === langQuery)

  return lang || i18nConfig.defaultLanguage
}

export default class MyDocument extends Document {
  render() {
    return (
      <Html lang={documentLang(this.props)}>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
```

Is it possible to change lang value at html tag when changing language without page reload?
[Project repository](https://github.com/haw0k/gloria-logistic) 
[Project address](https://gloria-logistic.haw0k.now.sh/en)

**Comment by aralroca** [comment]
Hey @haw0k  thank you to report this.

This is because the Document code is not executed on the client-side.

You can just add a hook on your `_app.js` like:

```js
function useChangeLangHTML(){
  const { lang } = useTranslation()
  useEffect(() => document.querySelector("html").lang = lang, [lang])
}
```

However, maybe we can add a similar logic to `Router.pushI18n`,  `Router.replaceI18n` and `Link` component (on onClick event). It sounds reasonable to me.

**Comment by haw0k** [comment]
Would you give more specific instructions to resolve the problem please?

**Comment by aralroca** [comment]
@haw0k I did a PR that solves this 😊. So you don't need to do anything special. Just wait until `0.16.0` version. However, I'm going to pre-release this change under a canary today if you want to try it today!

**Comment by aralroca** [comment]
@haw0k I pre-released under `0.16.0-canary.3`. Can you try this version if it works now? 😊 Thanks!

**Comment by haw0k** [comment]
`yarn dev` displayed  `Invalid hook call` error:
```
$ yarn dev
yarn run v1.22.4
$ next-translate && next dev
Building pages | from pages_ to pages
� /business [ 'common', 'common' ]
� / [ 'common' ]
� /projects/[id] [ 'common' ]
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
Warning: Detected next.config.js, no exported configuration found. https://err.sh/zeit/next.js/empty-configuration
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (D:\work\gloria-logistic\app\node_modules\next-translate\node_modules\react\cjs\react.development.js:1465:13)
    at useContext (D:\work\gloria-logistic\app\node_modules\next-translate\node_modules\react\cjs\react.development.js:1473:20)
    at I18nProvider (D:\work\gloria-logistic\app\node_modules\next-translate\I18nProvider.js:1:2014)
    at processChild (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at render (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\render.js:83:16)
    at Object.renderPage (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\render.js:419:16)
    at Function.getInitialProps (D:\work\gloria-logistic\app\.next\server\static\development\pages\_document.js:304:19)
    at Object.loadGetInitialProps (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\lib\utils.js:59:29)
    at Object.renderToHTML (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\render.js:423:36)
    at async DevServer.renderToHTMLWithComponents (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\next-server.js:651:26)
    at async DevServer.renderToHTML (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\next-server.js:798:28)
    at async DevServer.renderToHTML (D:\work\gloria-logistic\app\node_modules\next\dist\server\next-dev-server.js:19:539)
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (D:\work\gloria-logistic\app\node_modules\next-translate\node_modules\react\cjs\react.development.js:1465:13)
    at useContext (D:\work\gloria-logistic\app\node_modules\next-translate\node_modules\react\cjs\react.development.js:1473:20)
    at I18nProvider (D:\work\gloria-logistic\app\node_modules\next-translate\I18nProvider.js:1:2014)
    at processChild (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (D:\work\gloria-logistic\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at render (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\render.js:83:16)
    at Object.renderPage (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\render.js:419:16)
    at Function.getInitialProps (D:\work\gloria-logistic\app\.next\server\static\development\pages\_document.js:304:19)
    at Object.loadGetInitialProps (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\lib\utils.js:59:29)
    at Object.renderToHTML (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\render.js:423:36)
    at async DevServer.renderToHTMLWithComponents (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\next-server.js:651:26)
    at async DevServer.renderToHTML (D:\work\gloria-logistic\app\node_modules\next\dist\next-server\server\next-server.js:798:28)
    at async DevServer.renderToHTML (D:\work\gloria-logistic\app\node_modules\next\dist\server\next-dev-server.js:19:539)
```

**Comment by aralroca** [comment]
I can't reproduce this error. Can you share your code?

**Comment by aralroca** [comment]
@haw0k on `0.17.0-canary.1` is available the helper:

```js
import Document, { Html, Head, Main, NextScript } from 'next/document'
import documentLang from 'next-translate/documentLang'

export default class MyDocument extends Document {
  render() {
    return (
      <Html lang={documentLang(this.props)}>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
```
