### ISSUE TITLE
Internal Server Error - The default export is not a React Component in page: "/_app"

### ISSUE THREAD

**Issue by RobertoCorreale** [vinissimus/next-translate#392]
Hi there,

When i run `npm run dev` on the basic example and i open localhost:3000 I get the following error: 

```
Error: The default export is not a React Component in page: "/_app"
    at renderToHTML (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/render.js:21:2493)
    at /Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:98:126
    at __wrapper (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/lib/coalesced-function.js:1:341)
    at /Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/lib/coalesced-function.js:1:377
    at DevServer.renderToHTMLWithComponents (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:123:393)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DevServer.renderToHTML (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:124:473)
    at async DevServer.renderToHTML (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:71:236)
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
Error: The default export is not a React Component in page: "/_app"
    at renderToHTML (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/render.js:21:2493)
    at /Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:98:126
    at /Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:91:148
    at DevServer.renderToHTMLWithComponents (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:123:393)
    at DevServer.renderErrorToHTML (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:125:338)
    at async DevServer.renderErrorToHTML (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/server/next-dev-server.js:34:1204)
    at async DevServer.renderToHTML (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:124:1228)
    at async DevServer.renderToHTML (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:71:236)
    at async Object.fn (/Users/roberto/Downloads/next-translate-master/examples/basic/node_modules/next/dist/next-server/server/next-server.js:55:618)
```

I'm using node v14.15.1.
When I open the page on browser (localhost:3000) I get "Internal server error".
Anyone can help me?

Thank you

**Comment by RobertoCorreale** [comment]
Update React from 16.8 to 17.0.1 solved the issue
