### ISSUE TITLE
getServerSideProps loading on dynamic page with HOC

### ISSUE THREAD

**Issue by rohanrajpal** [vinissimus/next-translate#423]
I have the following directory structure
```
pages/[storename]/index.tsx
```

and it looks like 
```ts
// pages/[storename]/index.js
import React from 'react';
import Head from 'next/head';
import { withUrqlClient } from 'next-urql';
const Index = () => {
  const [result] = useQuery({
    query: '{ test }',
  });
  // ...
};
export default withUrqlClient((_ssrExchange, ctx) => ({
  // ...add your Client options here
  url: 'http://localhost:3000/graphql',
},{ssr:true}))(Index);
```

Even after that i'm getting the error
```bash
Error: You can not use getInitialProps with getServerSideProps. Please remove getInitialProps. /[storename]
    at renderToHTML (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/render.js:21:1728)
    at /home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:98:126
    at /home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:91:148
    at DevServer.renderToHTMLWithComponents (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:123:393)
    at DevServer.renderToHTML (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:124:885)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async DevServer.renderToHTML (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:71:236)
    at async Object.fn (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:55:618)
    at async Router.execute (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:65:1023)
    at async DevServer.handleRequest (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:33:450)
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
Error: You can not use getInitialProps with getServerSideProps. Please remove getInitialProps. /[storename]
    at renderToHTML (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/render.js:21:1728)
    at /home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:98:126
    at /home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:91:148
    at DevServer.renderToHTMLWithComponents (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:123:393)
    at DevServer.renderToHTML (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:124:885)
    at async DevServer.renderToHTML (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:71:236)
    at async Object.fn (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:55:618)
    at async Router.execute (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:65:1023)
    at async DevServer.handleRequest (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:33:450)
Error: You can not use getInitialProps with getServerSideProps. Please remove getInitialProps. /[storename]
    at renderToHTML (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/render.js:21:1728)
    at /home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:98:126
    at /home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:91:148
    at DevServer.renderToHTMLWithComponents (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:123:393)
    at DevServer.renderToHTML (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:124:885)
    at async DevServer.renderToHTML (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:71:236)
    at async Object.fn (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:55:618)
    at async Router.execute (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:65:1023)
    at async DevServer.handleRequest (/home/rohan/Documents/Github/startup/storefront/node_modules/next/dist/next-server/server/next-server.js:33:450)

```

my intl config is
```json
{
  "locales": ["en-IN", "hi"],
  "defaultLocale": "en-IN",
  "pages": {
    "*": ["common"]
  }
}
```

Can anyone help me out with this?

**Comment by aralroca** [comment]
@rohanrajpal Looks a bug. Next-translate is using `getServerSideProps` but It should use `getInitialProps` by default in this case. In the docs:

> - **`getInitialProps`**. This is the **default method for these pages that use a HoC**. This is in order to avoid conflicts because HoC could overwrite a `getInitialProps`.


- https://github.com/vinissimus/next-translate/tree/1.0.1#how-are-translations-loaded

And `withUrqlClient` is using `getInitialProps`:

- https://github.com/FormidableLabs/next-urql/blob/master/src/with-urql-client.tsx#L52

So for some reason is not detected as HOC... Thanks to report it ☺️

As a temporal solution. Remember that this is only the default method. If you write an empty `getInitialProps` on your page, it should use the`getInitialProps` to load the translations. Hope it helps.

**Comment by rohanrajpal** [comment]
> @rohanrajpal Looks a bug. Next-translate is using `getServerSideProps` but It should use `getInitialProps` by default in this case. In the docs:
> 
> > * **`getInitialProps`**. This is the **default method for these pages that use a HoC**. This is in order to avoid conflicts because HoC could overwrite a `getInitialProps`.
> 
> * https://github.com/vinissimus/next-translate/tree/1.0.1#how-are-translations-loaded
> 
> And `withUrqlClient` is using `getInitialProps`:
> 
> * https://github.com/FormidableLabs/next-urql/blob/master/src/with-urql-client.tsx#L52
> 
> So for some reason is not detected as HOC... Thanks to report it ☺️
> 
> As a temporal solution. Remember that this is only the default method. If you write an empty `getInitialProps` on your page, it should use the`getInitialProps` to load the translations. Hope it helps.

Yeahh I was thinking that this is a bug. I'll try out the empty getInitialprops. Thanks for the help!

**Comment by aralroca** [comment]
@rohanrajpal can you try [1.0.2-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.0.2-canary.2). It's already fixed 👍 Can you confirm? Thanks 🙏

**Comment by aralroca** [comment]
@rohanrajpal can you confirm it? 🙏  Thanks!

**Comment by aralroca** [comment]
@rohanrajpal I close it as it seems to be solved. If it continues to happen to you, comment on it and we will reopen it.
