### ISSUE TITLE
MyApp is not defined     at Module../pages/_app.js

### ISSUE THREAD

**Issue by sami-lab** [vinissimus/next-translate#431]
i am trying to translate my website into nn_ locality, but after introducing package to my project. this error is coming...
### ReferenceError: MyApp is not defined
    at Module../pages/_app.js (D:\Files and Softwares\ass\React apps\Hello-Next\nextjs\.next\server\pages\_app.js:3640:1)
    at __webpack_require__ (D:\Files and Softwares\ass\React apps\Hello-Next\nextjs\.next\server\pages\_app.js:29:31)
    at Object.0 (D:\Files and Softwares\ass\React apps\Hello-Next\nextjs\.next\server\pages\_app.js:5009:18)
    at __webpack_require__ (D:\Files and Softwares\ass\React apps\Hello-Next\nextjs\.next\server\pages\_app.js:29:31)
    at D:\Files and Softwares\ass\React apps\Hello-Next\nextjs\.next\server\pages\_app.js:124:18
    at Object.<anonymous> (D:\Files and Softwares\ass\React apps\Hello-Next\nextjs\.next\server\pages\_app.js:127:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
my website is working fine before using next-translate. By just removing next.config.js, everything works properly. 
**i18n.json**..
```
`{
    "locales": ["nn_"],
    "defaultLocale": "nn_",
    "pages": {
      "*": ["common"],
      "/": ["index"],
      "/quote": ["quote"],
      "/aboutus": ["aboutus"]
    }
  }`
```
**next.config.json**
```
`const nextTranslate = require('next-translate');

module.exports = nextTranslate();
`
```
![image](https://user-images.githubusercontent.com/56019715/103456179-87078100-4d15-11eb-9f2f-321c2c10dd9b.png)

**Comment by sami-lab** [comment]
just solved this issue by moving export from export  function MyApp to  export default MyApp;
