### ISSUE TITLE
docker run throwing error with next-translate library

### ISSUE THREAD

**Issue by avisek1269** [vinissimus/next-translate#438]
I am using this dockerfile https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile.multistage .

It throws below error while running the image.

`Loaded env from /app/.env.production
Error: Cannot find module '/app/i18n'
Require stack:
- /app/node_modules/next-translate/lib/cjs/plugin/index.js
- /app/node_modules/next-translate/lib/cjs/index.js
- /app/next.config.js
- /app/node_modules/next/dist/next-server/server/config.js
- /app/node_modules/next/dist/next-server/server/next-server.js
- /app/node_modules/next/dist/server/next.js
- /app/node_modules/next/dist/server/lib/start-server.js
- /app/node_modules/next/dist/cli/next-start.js
- /app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at nextTranslate (/app/node_modules/next-translate/lib/cjs/plugin/index.js:34:14)
    at Object.<anonymous> (/app/next.config.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {`

**Comment by aralroca** [comment]
@avisek1269 look that is missing the file `/app/i18n.js` isn't it?

**Comment by avisek1269** [comment]
I guessed that too @aralroca .
I tried that too but after adding it it throws 
Error: ENOENT: no such file or directory, scandir '/app/pages'
    at Object.readdirSync (node:fs:1044:3)
    at nextTranslate (/app/node_modules/next-translate/lib/cjs/plugin/index.js:50:18)
    at Object.<anonymous> (/app/next.config.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at loadConfig (/app/node_modules/next/dist/next-server/server/config.js:8:100) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/app/pages'

I did not understand why its asking for pages directory .

**Comment by aralroca** [comment]
@avisek1269 I guess is a duplicated of this issue: https://github.com/vinissimus/next-translate/issues/421 

is planned for the next version 1.0.2 😊 I hope that for now, the workaround proposed in the issue works for you.

**Comment by avisek1269** [comment]
Thanks @aralroca.  It works with this workaround.  I am closing this ticket as its kinda duplicate and its already planned for next release.  🎉

**Comment by karelbecerra** [comment]
This worked for me (dockerfile)
`COPY --from=builder /app/i18n.js ./i18n.js`
