### ISSUE TITLE
Cannot build _server.js with serverSideProps

### ISSUE THREAD

**Issue by gorkalaucirica** [vinissimus/next-translate#491]
In a use case where _server.js requires using serverSideProps, next-translate makes the build crash with the following error:

```
Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
Error: Error for page /_error: pages with `getServerSideProps` can not be exported. See more info here: https://err.sh/next.js/gssp-export
    at /node_modules/next/dist/export/worker.js:16:281
    at async node_modules/next/dist/build/tracer.js:1:1441
```

I was able to reproduce the issue in a repo: https://github.com/gorkalaucirica/next-translate-bug

`getInitialProps` is working properly but prints the following error:

```
🚨 [next-translate] In Next 10.x.x there is an issue related to i18n and getInitialProps. We recommend to replace getInitialProps to getServerSideProps on /_error.js. Issue: https://github.com/vercel/next.js/issues/18396
```

This happens in all 1.0.x versions.

**Comment by fernandojbf** [comment]
I don't know if related to this or not but I'm having an error related to the error page. 
Common namespaces (`*`: [....]) are not being added to the error page.

This is making my build to fail since is missing an array from one common translation.

Can you check if this can be related to your problem too?

I will try to get more information about my error but could be beneficial to check if could be the same root cause.

**Comment by underpr00f** [comment]
Same problem! Only replace from getServerSide to getInitialProps on _error page, help to fix problem on build. (But if I use getInitialProps, prints warning).

**Comment by aralroca** [comment]
This warning in `getInitialProps` will be solved after this PR will be merged on Next.js core: https://github.com/vercel/next.js/pull/21930

**Comment by amit0693** [comment]
I am getting same error while build 

npm run build


> build
> next build

info  - Checking validity of types  
warn  - No ESLint configuration detected. Run next lint to begin 
setup
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[    ] info  - Generating static pages (0/3){
  connectWallet: [AsyncFunction: connectWallet],
  currentAccount: undefined
}
info  - Generating static pages (3/3)
info  - Finalizing page optimization

Page                                       Size     First Load JS
┌ ○ /                                      32.2 kB         205 kB
├   /_app                                  0 B             173 kB
├ ○ /404                                   192 B           173 kB
└ λ /api/hello                             0 B             173 kB
+ First Load JS shared by all              173 kB
  ├ chunks/framework-e70c6273bfe3f237.js   42 kB
  ├ chunks/main-5d375b4bfedf1a40.js        28.2 kB
  ├ chunks/pages/_app-6d98083422e832e5.js  102 kB
  ├ chunks/webpack-5761f3a204ffdf4a.js     1.08 kB
  └ css/05ca771b20c627f0.css               2.33 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

git repo 
https://github.com/amit0693/CryptSwap
