### ISSUE TITLE
Support Blitz.js

### ISSUE THREAD

**Issue by BjoernRave** [vinissimus/next-translate#499]
It would be great if this library would work with [Blitz.js](https://blitzjs.com/).

Currently I get the following error:
```
/Users/bjoern/projects/myproject/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:187
                    throw err;
                    ^

Error: ENOENT: no such file or directory, scandir '/Users/bjoern/projects/myproject/pages'
    at Object.readdirSync (fs.js:872:3)
    at nextTranslate (/Users/bjoern/projects/myproject/node_modules/next-translate/lib/cjs/plugin/index.js:51:10)
    at Object.apply (/Users/bjoern/projects/myproject/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:183:36)
    at Object.<anonymous> (/Users/bjoern/projects/myproject/blitz.config.js:5:18)
    at Module._compile (/Users/bjoern/projects/myproject/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Module._load (internal/modules/cjs/loader.js:877:14)
    at Function._load (/Users/bjoern/projects/myproject/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:99:24)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/bjoern/projects/myproject/pages'
}
```

**Comment by flybayer** [comment]
Looks like it should work by setting `NEXT_TRANSLATE_PATH` env

For dev build: `NEXT_TRANSLATE_PATH='.blitz/caches/dev'
For production build: `NEXT_TRANSLATE_PATH='.blitz/caches/build'

But it could be zero-config if by changing this: https://github.com/vinissimus/next-translate/blob/master/src/plugin/index.ts#L9-L11

```diff
  const dir = path.resolve(
--    path.relative(process.cwd(), process.env.NEXT_TRANSLATE_PATH || '.')
++    path.relative(require('pkg-dir').sync() || process.cwd(), process.env.NEXT_TRANSLATE_PATH || '.')
  )
```

That would first try to find the location of next package.json up in the tree, otherwise fall back to process.cwd(). So then in dev that will resolve to `.blitz/caches/dev/package.json` and in prod build to `.blitz/caches/build/package.json`

**Comment by aralroca** [comment]
@flybayer I did a PR with your proposal

**Comment by BjoernRave** [comment]
Awesome. After that landed I will try to do a blitz recipe for it :)

**Comment by aralroca** [comment]
Already prereleased on [1.0.3-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.0.3-canary.2). I close the issue, if you have any comments please let me know and we will reopen it @flybayer @BjoernRave
