### ISSUE TITLE
ReferenceError: MyApp is not defined     at eval (webpack-internal:///./pages/_app.js:116:1)

### ISSUE THREAD

**Issue by nonoumasy** [vinissimus/next-translate#608]
I am getting the ...

```
ReferenceError: MyApp is not defined
    at eval (webpack-internal:///./pages/_app.js:116:1)
```

I tried using the suggested solution. However, I get a :
```
Syntax error: Identifier '__i18nConfig' has already been declared
Syntax error: Identifier '__appWithI18n' has already been declared
Syntax error: Identifier '__Page_Next_Translate__' has already been declared
```

MyApp.js
```
import {useEffect} from 'react';
import PropTypes from 'prop-types';
import Layout from '../components/Layout'
import __i18nConfig from '@next-translate-root/i18n'
import __appWithI18n from 'next-translate/appWithI18n'

export default function MyApp(props) {
  const { Component, pageProps } = props;

  return (
    <>
      < />
          <Layout>
            <Component {...pageProps} />
          </Layout>
    </>
  );
}

const __Page_Next_Translate__ = MyApp
MyApp.propTypes = {
  Component: PropTypes.any,
  pageProps: PropTypes.any,
};

export default __appWithI18n(__Page_Next_Translate__, {
  ...__i18nConfig,
  isLoader: true,
  skipInitialProps: true,
  loadLocaleFrom: (l, n) => import(`@next-translate-root/locales/${l}/${n}`).then(m => m.default),
});
```
i18n.json
```
{
	"locales": [ "ar", "de", "en", "es", "fr", "hi-IN", "ja", "pt", "ru", "zh" ],
	"defaultLocale": "en",
	"pages": {
		"*": [ "common" ],
		"/about": [ "about" ],
		"/": [ "home" ]
	}
}

```
next.config.js
```
const nextTranslate = require('next-translate')

module.exports = nextTranslate({
    images: {
        domains: ['img.youtube.com', 'firebasestorage.googleapis.com', 'cloudinary.com', 'res.cloudinary.com'],
    }
})
```

**Comment by aralroca** [comment]
@nonoumasy you don't need this in your `_app.js` because is added automatically by de webpack loader:

```js
export default __appWithI18n(__Page_Next_Translate__, {
  ...__i18nConfig,
  isLoader: true,
  skipInitialProps: true,
  loadLocaleFrom: (l, n) => import(`@next-translate-root/locales/${l}/${n}`).then(m => m.default),
});
```

You can transform your `_app.js` to:

```js
import PropTypes from 'prop-types';
import Layout from '../components/Layout'

export default function MyApp({ Component, pageProps } ) {
  return <Layout><Component {...pageProps} /></Layout>
}

MyApp.propTypes = {
  Component: PropTypes.any,
  pageProps: PropTypes.any,
};
```

Sorry for not answering until now, I hope you have it fixed. I close the issue, if it's another problem comment here and we reopen the issue to solve it. Thanks
