### ISSUE TITLE
Dont`t consume NextJs useRouter hook in I18nProvider

### ISSUE THREAD

**Issue by gurkerl83** [vinissimus/next-translate#833]
The current implementation of NextJs useRouter hook returns the entire context object as a consumer.

```
export function useRouter(): NextRouter {
  return React.useContext(RouterContext)
}
```

Part of the context is the property asPath which includes the query and hash shown in the browser. For in-page navigation purposes, e.g., using a table of content, the hash gets used to navigate to the respective page sections.

Changing minor navigation aspects like the should not result in a change of asPath, but in NextJs it results in a different context. Based on the useRouter implementation, a re-rendering occurs.

Using the NextJs useRouter hook in I18nProvider, the consequence is that the Provider re-creates itself anytime a minor in-page navigation gets triggered. 

To avoid this, provide the values from the Next context required within I18nProvider from the outside like that.

Memo in _app

```
const {
   query: { slug },
   locale,
   defaultLocale,
} = useRouter();

const component = useMemo(() => {
   return (
      <I18nProvider
         lang={__lang}
         namespaces={__namespaces}
         // provide relevant properties from the outside
         locale={locale}
         defaultLocale={defaultLocale}
      >
         <Component {...pageProps} />
      </I18nProvider>
   );
}, [slug, locale]); // re-create the component instance when slug or locale changes
```

Thx!

**Comment by aralroca** [comment]
Feel free to PR @gurkerl83 ! Thanks for your proposal!

**Comment by gittygoo** [comment]
Not sure if the same but with nextjs 13.5 i am getting the same (and strangely only with NODE_ENV=test):

Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
    at useRouter (C:\app\client\node_modules\next\dist\client\router.js:146:15)
    at I18nProvider (C:\app\client\node_modules\next-translate\lib\cjs\I18nProvider.js:50:37)
 
 
 downgrading to nextjs 13.4.19 solves it

**Comment by BjoernRave** [comment]
@gittygoo I am facing the same problem

**Comment by cykoder** [comment]
I get the same issue with next 14 with or without NODE_ENV=test

**Comment by TheMikeyRoss** [comment]
im also getting the same issue in Next v14.2.2 and v14.2.3
